### ISSUE TITLE
Implement new landing page based on the provided designs

### ISSUE THREAD

**Issue by mdrokz** [maestro3517/FlutterQRApp#18]
# Tasks

- [x] Add floating button to open QR scanner
- [x] Redirect to landing page after login
- [x] Create components based on design

# Design

![WhatsApp Image 2022-06-29 at 12 08 29 PM](https://user-images.githubusercontent.com/33598169/176444163-beb693f1-3aec-4aad-ab18-7de6a37b7316.jpeg)
![WhatsApp Image 2022-06-29 at 12 12 06 PM](https://user-images.githubusercontent.com/33598169/176444182-3321bac7-1c4b-49b0-9fe1-51b2607348a0.jpeg)

**Comment by mdrokz** [comment]
closing with #22
