### ISSUE TITLE
Refactor Details page based on the provided designs

### ISSUE THREAD

**Issue by mdrokz** [maestro3517/FlutterQRApp#19]
# Tasks
 
- [x] Implement Card pills component for display
- [x] Implement Image based card component for heading
- [x] Divide details into two card layouts

# Design

![WhatsApp Image 2022-06-29 at 12 10 55 PM](https://user-images.githubusercontent.com/33598169/176444894-31b676bc-4a5f-4cb0-be0a-7e5aa1e830cc.jpeg)
![WhatsApp Image 2022-06-29 at 12 08 28 PM](https://user-images.githubusercontent.com/33598169/176444921-677ea1b7-fda7-4962-81b5-a8beb531c69d.jpeg)
